# Storage for table names to remove

tables_to_remove = [
    'The Barbarian',
    'The Bard',
    'The Cleric',
    'The Druid',
    'The Fighter',
    'The Monk',
    'The Paladin',
    'The Ranger',
    'The Rogue',
    'The Sorcerer',
    'The Warlock',
    'The Wizard',
    'Character Advancement',
    'Multiclass Spellcaster: Spell Slots per Spell Level',
    'Standard Exchange Rates',
    'Ability Scores and Modifiers',
    'Animated Object Statistics',
    'Precipitation',
    'Temperature',
    'Wind',
    'Damage Severity by Level',
    'Trap Save DCs and Attack Bonuses',
    'Apparatus of the Crab Levers',
    ('Armor (light, medium, or heavy), rare (requires attunement) You have ',
     'resistance to one type of damage while you wear this armor. The GM ',
     'chooses the type or determines it randomly from the options below.'),
    'Gray Bag of Tricks',
    'Rust Bag of Tricks',
    'Tan Bag of Tricks',
    'Hit Dice by Size',
    'Proficiency Bonus by Challenge Rating',
    'Experience Points by Challenge Rating',
]
